### PR TITLE
build: fix tarantool build failure on xcode 12.5

### PR DESCRIPTION
**Pull request by EvgenyMekhanik**
build: fix tarantool build failure on xcode 12.5
    
    `VERSION` file in small is treated as C++ standard library
    on a filesystem with case-insensitive names. So we create
    `include` subfolder and then `include/small` in this project
    and add symlink `include/small/*.h -> small/*.h`. Then we change
    `include_directories` in tarantool CMake from the root of this
    project to `include` subfolder.
    Part of #6076

### CODE REVIEW

**Comment by iskander232** [comment]
Why did you rename `features -> small_features`?

**Review by iskander232 — APPROVED** [review]
LGTM

**Review by sergos — APPROVED** [review]
I would like @alyapunov have a look at the changes.

LGTM.

**Comment by Totktonada** [comment]
1. It would be good to leave a link to the issue, where everything was started (tarantool's one).
2. It would be good to reflect the new changes in the PR description (say, just copy it from the new commit message).
3. Should not we create `include/small/*.h -> ../small/*.h` symlinks instead of just `include/small -> ../small`? It looks a bit strange to have *.c files in an `include/` directory.

Aside of this, no objections from me.

**Review by Totktonada — APPROVED** [review]
I have no strict objections: the above ones are a kind of wishes. I'm generally okay with any you decision: whether to follow my comments or don't.

**Review by alyapunov — APPROVED** [review]

**Pull request merged**
